name: Auto Release

on:
  push:
    paths:
      - Prothom Alo/2024/**  # This triggers workflow for changes within Prothom Alo/2024 directory

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Listen for webhook events
        uses: actions/github-script@v6
        with:
          github-script: |
            const newFiles = context.payload.commits.flatMap(commit => commit.added);
            const isNewFileIn2024 = newFiles.some(file => file.startsWith('Prothom Alo/2024/'));
            if (isNewFileIn2024) {
              console.log('New file detected in Prothom Alo/2024 directory!');
              core.setOutput('create_release', true);
            } else {
              console.log('No new file detected in Prothom Alo/2024 directory.');
            }
      - name: Create Release Draft (if new file)
        uses: release-drafter/release-drafter@v6
        if: ${{ steps.listen-for-webhook-events.outputs.create_release == 'true' }}
        with:
          release-notes: ${{ github.event.commits[0].commit.message }}  # Uses commit message for release notes

